spring.application.name=urlshortkaro

# Flyway
spring.flyway.enabled=true

# JPA
spring.jpa.hibernate.ddl-auto=validate

# Active Profile
spring.profiles.active=dev

# URL Shortener
app.url.default-expiry-days=30
app.url.short-code-length=7
app.url.max-retry-count=5