spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/urlshortkaro
    username: postgres
    password: postgres

  jpa:
    show-sql: true

server:
  port: 8080

app:
  url:
    base-url: http://localhost:8080